version: '2'
services:
  web:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '7777:7777'
    environment:
      - PROJECT_PATH=/Users/tbd/Desktop/Github
    command: 'start'
